from PyQt6.QtWidgets import *
from PyQt6.QtGui import *
from PyQt6.QtCore import*
class singerUI(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()
    def initUI(self):
        super().__init__()
        layout=QVBoxLayout(self)
        singer_layout=QGridLayout(self)
        self.mayday=QToolButton(self)
        self.mayday.setFixedSize(100,100)
        self.mayday.setIcon(QIcon('./img/mayday.png'))
        self.mayday.setIconSize(QSize(90,90))
        self.mayday.setToolTip('五月天')
        self.mayday.setStyleSheet("background-color:#FFF8D7")
        self.nine=QToolButton(self)
        self.nine.setFixedSize(100,100)
        self.nine.setIcon(QIcon('./img/nine.png'))
        self.nine.setIconSize(QSize(90,90))
        self.nine.setToolTip('陳零九')
        self.nine.setStyleSheet("background-color:#FFF8D7")
        self.jay=QToolButton(self)
        self.jay.setFixedSize(100,100)
        self.jay.setIcon(QIcon('./img/jay.png'))
        self.jay.setIconSize(QSize(90,90))
        self.jay.setToolTip('周杰倫')
        self.jay.setStyleSheet("background-color:#FFF8D7")
        self.JJ=QToolButton(self)
        self.JJ.setFixedSize(100,100)
        self.JJ.setIcon(QIcon('./img/JJ.png'))
        self.JJ.setIconSize(QSize(90,90))
        self.JJ.setToolTip('林俊傑')
        self.JJ.setStyleSheet("background-color:#FFF8D7")
        self.eric=QToolButton(self)
        self.eric.setFixedSize(100,100)
        self.eric.setIcon(QIcon('./img/eric.png'))
        self.eric.setIconSize(QSize(90,90))
        self.eric.setToolTip('周興哲')
        self.eric.setStyleSheet("background-color:#FFF8D7")
        self.wolfs=QToolButton(self)
        self.wolfs.setFixedSize(100,100)
        self.wolfs.setIcon(QIcon('./img/wolfs.png'))
        self.wolfs.setIconSize(QSize(90,90))
        self.wolfs.setToolTip('五堅情')
        self.wolfs.setStyleSheet("background-color:#FFF8D7")
        
        singer_layout.addWidget(self.mayday,0,0)
        singer_layout.addWidget(self.nine,0,1)
        singer_layout.addWidget(self.jay,1,0)
        singer_layout.addWidget(self.JJ,1,1)
        singer_layout.addWidget(self.eric,2,0)
        singer_layout.addWidget(self.wolfs,2,1)

        self.play=QPushButton(self)
        self.pause=QPushButton(self)
        self.play.setText('play')
        self.pause.setIcon(QIcon('./img/pause.png'))

        self.songlist=QListWidget(self)
        self.home=QPushButton(self)
        self.home.setText("home")
        self.home.setIcon(QIcon('./img/home.png'))
        self.play.setStyleSheet("background-color:	#FFF8D7")
        self.pause.setStyleSheet("background-color:	#FFF8D7")
        self.songlist.setStyleSheet("background-color:	#FFF8D7")
        self.home.setStyleSheet("background-color:	#FFF8D7")
        layout.addLayout(singer_layout)
        layout.addWidget(self.songlist)
        layout.addWidget(self.play)
        layout.addWidget(self.pause)
        layout.addWidget(self.home)
        self.play.setVisible(False)
        self.pause.setVisible(False)
        self.setLayout(layout) 
